## 1.	

#### Write a code to import NumPy into your script. Check the version of NumPy installed.

In [1]:
import numpy as np

In [2]:
# Checking the version of NumPy
np.__version__

'1.24.3'

## 2.	

#### Here is a list below:
#### list1 = [2, 3, 4, 6]

#### Create a one-dimensional array from the list above. Write another code to check the shape and size of your array.


In [3]:
list1 = [2, 3, 4, 6]

arr = np.array(list1)
arr

array([2, 3, 4, 6])

In [4]:
# Checking shape of array
arr.shape

(4,)

In [5]:
# Checking size of array
arr_size = np.size(arr)
print("The Number of Itemms in the array: ", arr_size)

The Number of Itemms in the array:  4


#### Write a function that takes this array and returns a new array with all the values in the original array reversed.

In [6]:
# Using function to reverse array
def reverse_array(array):
    return array[::-1]

# Creating an array
arr = np.array(list1)

# Reversing array using function
arr_reversed = reverse_array(arr)
arr_reversed

array([6, 4, 3, 2])

#### Another method

In [7]:
# Creating an array
arr = np.array(list1)

# Reversing array using flip
flip_arr = np.flip(arr, axis=None)
flip_arr

array([6, 4, 3, 2])

### 3.

#### list1 = [2, 3, 4, 6]

#### list2 = [8, 10, 12, 14]

#### Create an array from the two lists above. Then write code to check the shape, dimensions,  and data type of the array.


In [8]:
list1 = [2, 3, 4, 6]
list2 = [8, 10, 12, 14]

# Creating array from two lists
arr = np.array([list1, list2])
arr

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14]])

In [9]:
# Checking shape of the array
arr.shape

(2, 4)

In [10]:
# Checking dimensions of the array
arr.ndim

2

In [11]:
# checking the dtype of array
arr.dtype

dtype('int32')

## 4.

#### list1 = [2, 3, 4, 6]

#### list2 = [8, 10.1, 12, 14]

#### list3 = [16, 18, 20, 22.1]

#### Create an array from the three (3) lists above. Take note that some of the lists contain floats. Create an array that will have an int64 data type


In [12]:
list1 = [2, 3, 4, 6]
list2 = [8, 10.1, 12, 14]
list3 = [16, 18, 20, 22.1]

# Create an array from the three lists
arr = np.array([list1, list2, list3])


# Convert the array to int64 data type
arr = arr.astype(np.int64)
print(arr)

[[ 2  3  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [13]:
# Print array data type
print("New arr data type:", arr.dtype)

New arr data type: int64


#### Another method

In [14]:
list1 = [2, 3, 4, 6]
list2 = [8, 10.1, 12, 14]
list3 = [16, 18, 20, 22.1]

arr = np.array([list1,list2, list3], dtype='int64')
arr

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]], dtype=int64)

## 5.	

#### Is it possible to create an array of both floats and integers?

In [15]:
# list of integers and floats
lst = [1, 2.5, 3, 4,2, 5]

# Creating an array from a list of floats and integers
my_array = np.array(lst)
my_array.dtype

dtype('float64')