## 1.	

#### Create an array using the list above. Write a code to sort the array in ascending order; first sort by columns, then by rows. Create a new variable for each of the sorted arrays.

In [1]:
import numpy as np

list1 = [[12, 34, 56], [12, 13, 8], [6, 5, 10]]

# Creating array from list
array1 = np.array(list1)

# Sort the array in ascending order by columns
sorted_array_column = np.sort(array1, axis = 0)
sorted_array_column

array([[ 6,  5,  8],
       [12, 13, 10],
       [12, 34, 56]])

Sorting by rows

In [2]:
list1 = [[12, 34, 56], [12, 13, 8], [6, 5, 10]]

# Creating array from list
array1 = np.array(list1)

# Sort array in ascending order by rows
sorted_array_row = np.sort(array1, axis=1)
sorted_array_row

array([[12, 34, 56],
       [ 8, 12, 13],
       [ 5,  6, 10]])

## 2.	

#### Using NumPy slicing, write a code that slices these numbers in this order [8, 12, 56] from the array sorted by columns (question 1 ). Create a new variable. 

In [3]:
# using slicing to create a new array
new_array = np.array([sorted_array_column[0][2], 
                      sorted_array_column[1][0], 
                      sorted_array_column[2][2]]
                    )
new_array

array([ 8, 12, 56])

## 3. 

#### Create a 2-dimensional array of random integers between 100 and -100 of shape (3, 3). Use numpy.where() function to replace all negative values in the array with 0. Use seed to save the random numbers generated.

In [4]:
# Generating data
rng = np.random.default_rng(seed = 42)
array2 = rng.integers(low = -100, high = 100, size=(3, 3))
array2

array([[-83,  54,  30],
       [-13, -14,  71],
       [-83,  39, -60]], dtype=int64)

In [5]:
array2 = np.where(array2 < 0, 0, array2)
array2

array([[ 0, 54, 30],
       [ 0,  0, 71],
       [ 0, 39,  0]], dtype=int64)

## 4.	

#### Here is a list below:

#### list1 = [[12, 23, 34, 34], [13, 13, 20, 21]]

#### Create an array from the list above.

#### Using np.unique() function, return the unique elements in a the array and return the counts of each unique element (how many times each element appears in the list).


In [6]:
list1 = [[12, 23, 34, 34, 35], [13, 13, 13, 20, 21]]

# Creating an array
array3 = np.array(list1)

# use np.unique to find the unique elements in the array 
unique_elements, elements_count = np.unique(array3, return_counts=True)

print("Unique Elements:", unique_elements)
print("Elements count:", elements_count)

Unique Elements: [12 13 20 21 23 34 35]
Elements count: [1 3 1 1 1 2 1]


## 5.	

#### Using the np.flatten() function to flatten the nested array you created in question 4.

In [7]:
# Using flatten method to flatten a nested array
array4 = array3.flatten()
array4

array([12, 23, 34, 34, 35, 13, 13, 13, 20, 21])